INSERT INTO business_entries (
  slug, name, category, title, subtitle, description, navigation_type, href, redirect_path, status, sort_order, cta_label, theme, media, seo
) VALUES 
(
  'cosmetic',
  'VAVAW Cosmetic',
  'Cosmetic',
  'VAVAW Cosmetic',
  'Premium cosmetic line by VAVAW.',
  'A dedicated cosmetic collection under the VAVAW ecosystem.',
  'internal',
  '/cosmetic',
  '/go/cosmetic',
  'active',
  1,
  'Explore Cosmetic',
  '{"primary": "#e11d48", "secondary": "#9f1239", "background": "#0f0507", "text": "#ffffff", "accent": "#fb7185"}'::jsonb,
  '{"backgroundImage": "/media/hero/cosmetic-hero.jpg", "previewImage": "/media/preview/cosmetic-preview.jpg", "ogImage": "/media/og/cosmetic-og.jpg"}'::jsonb,
  '{"title": "VAVAW Cosmetic - Premium Beauty Line", "description": "Discover the VAVAW Cosmetic collection.", "keywords": ["vavaw", "cosmetic", "beauty", "skincare", "premium"], "canonicalUrl": "https://vavaw.vn/cosmetic"}'::jsonb
),
(
  'beauty',
  'VAVAW Beauty & Co',
  'Beauty & Care',
  'VAVAW Beauty & Co',
  'A beauty and care destination by VAVAW.',
  'A dedicated beauty brand experience within the VAVAW ecosystem.',
  'external-app',
  'https://beauty.vavaw.vn',
  '/go/beauty',
  'coming-soon',
  2,
  'Visit Beauty & Co',
  '{"primary": "#0284c7", "secondary": "#0369a1", "background": "#020617", "text": "#ffffff", "accent": "#38bdf8"}'::jsonb,
  '{"backgroundImage": "/media/hero/beauty-hero.jpg", "previewImage": "/media/preview/beauty-preview.jpg", "ogImage": "/media/og/beauty-og.jpg"}'::jsonb,
  '{"title": "VAVAW Beauty & Co", "description": "Beauty and care destination.", "keywords": ["vavaw", "beauty", "care", "skincare"], "canonicalUrl": "https://beauty.vavaw.vn"}'::jsonb
),
(
  'franchise',
  'VAVAW Franchise',
  'Franchise',
  'VAVAW Franchise',
  'Franchise opportunities with VAVAW.',
  'Learn about business partnership and franchise opportunities.',
  'external-app',
  'https://franchise.vavaw.vn',
  '/go/franchise',
  'coming-soon',
  3,
  'Explore Franchise',
  '{"primary": "#d97706", "secondary": "#b45309", "background": "#0c0a09", "text": "#ffffff", "accent": "#fbbf24"}'::jsonb,
  '{"backgroundImage": "/media/hero/franchise-hero.jpg", "previewImage": "/media/preview/franchise-preview.jpg", "ogImage": "/media/og/franchise-og.jpg"}'::jsonb,
  '{"title": "VAVAW Franchise", "description": "Franchise opportunities with VAVAW.", "keywords": ["vavaw", "franchise", "business", "partnership"], "canonicalUrl": "https://franchise.vavaw.vn"}'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  description = EXCLUDED.description,
  navigation_type = EXCLUDED.navigation_type,
  href = EXCLUDED.href,
  redirect_path = EXCLUDED.redirect_path,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  cta_label = EXCLUDED.cta_label,
  theme = EXCLUDED.theme,
  media = EXCLUDED.media,
  seo = EXCLUDED.seo;
