export const COSMETIC_VI_COPY_MAP = {
  "Quy trình phục hồi làm dịu được thiết kế để khôi phục sự thoải mái, độ ẩm và sức đề kháng cho làn da.": "Quy trình phục hồi làm dịu, hỗ trợ khôi phục cảm giác dễ chịu, độ ẩm và khả năng tự bảo vệ của làn da.",

  "Gentle Activation Renew Ampoule — kích hoạt tái tạo tế bào và độ rạng rỡ.": "Gentle Activation Renew Ampoule — hỗ trợ quá trình làm mới làn da và cải thiện vẻ rạng rỡ.",

  "Bắt đầu với sữa rửa mặt lâm sàng dịu nhẹ để loại bỏ tạp chất mà không làm ảnh hưởng đến hệ vi sinh trên da.": "Bắt đầu với bước làm sạch dịu nhẹ để loại bỏ tạp chất mà vẫn hỗ trợ duy trì cảm giác cân bằng tự nhiên của da.",

  "Gel làm dịu da với phức hợp Cica 7 chiết xuất giúp xoa dịu làn da nhạy cảm và phục hồi hàng rào bảo vệ.": "Gel làm dịu da với phức hợp Cica 7 chiết xuất, hỗ trợ làm dịu làn da nhạy cảm và củng cố hàng rào bảo vệ da.",

  "Phục hồi và tái tạo tế bào": "Phục hồi & hỗ trợ làm mới làn da",

  "The Premium RAW Skincare System": "Hệ thống chăm sóc da RAW cao cấp",
  "Scientific beauty, refined into a pure Korean skincare ritual.\n\nVAVAW is a clinical Korean cosmetic system designed to restore the skin from its origin — pure, balanced, and resilient.": "Vẻ đẹp khoa học, được tinh chỉnh thành nghi thức chăm sóc da Hàn Quốc thuần khiết.\n\nVAVAW là hệ mỹ phẩm Hàn Quốc định hướng lâm sàng, được phát triển để hỗ trợ làn da phục hồi từ nền tảng — tinh khiết, cân bằng và bền vững.",
  "Scientific Beauty": "Vẻ đẹp khoa học",
  "Premium Program": "Chương trình chăm sóc cao cấp",
  "Functional Cosmetics": "Mỹ phẩm chức năng",
  "SIGNATURE RECOVERY COLLECTION": "BỘ SẢN PHẨM PHỤC HỒI ĐẶC TRƯNG",
  "Signature Recovery Collection": "Bộ sản phẩm phục hồi đặc trưng",
  "A complete Korean clinical skincare ritual for recovery, hydration, radiance, and skin barrier support.": "Nghi thức chăm sóc da Hàn Quốc định hướng lâm sàng, hỗ trợ phục hồi, cấp ẩm, cải thiện vẻ rạng rỡ và củng cố hàng rào bảo vệ da.",
  "EXPLORE THE RITUAL": "KHÁM PHÁ NGHI THỨC",
  "CLINICAL INSIGHT": "GÓC NHÌN LÂM SÀNG",
  "FEATURED SET": "BỘ SẢN PHẨM NỔI BẬT",
  "RECOVERY RITUAL · 6 STEPS": "NGHI THỨC PHỤC HỒI · 6 BƯỚC",
  "PEPTIDE COMPLEX": "PHỨC HỢP PEPTIDE",
  "VAVAW is a clinical Korean cosmetic system designed to restore the skin from its origin — pure, balanced, and resilient.": "VAVAW là hệ mỹ phẩm Hàn Quốc định hướng lâm sàng, được phát triển để hỗ trợ làn da phục hồi từ nền tảng — tinh khiết, cân bằng và bền vững.",
  "Clinical skincare system shaped by professional care standards — developed for visible, lasting results.": "Hệ chăm sóc da định hướng lâm sàng, được phát triển theo tiêu chuẩn chăm sóc chuyên nghiệp để mang lại hiệu quả rõ ràng và bền vững.",
  "Personalized skincare experience for modern skin concerns — designed for spa, clinic, and home ritual.": "Trải nghiệm chăm sóc da cá nhân hóa cho các vấn đề da hiện đại — phù hợp cho spa, clinic và routine tại nhà.",
  "Korean-developed formulas designed for visible skin recovery, balancing efficacy with elegance.": "Công thức phát triển theo định hướng Hàn Quốc, hỗ trợ phục hồi làn da rõ rệt và cân bằng giữa hiệu quả với sự tinh tế.",
  "The complete skin\nrecovery ritual.": "Nghi thức phục hồi da\ntoàn diện.",
  "A complete Korean clinical skincare ritual designed to cleanse, prepare, treat, seal, and protect the skin.": "Nghi thức chăm sóc da lâm sàng Hàn Quốc toàn diện được thiết kế để làm sạch, chuẩn bị, đặc trị, khóa ẩm và bảo vệ da.",
  "SIGNATURE RECOVERY SYSTEM": "HỆ THỐNG PHỤC HỒI ĐẶC TRƯNG",
  "Daily Clinical Skincare Routine": "Nghi thức chăm sóc da lâm sàng hàng ngày",
  "Answer a few quick questions to discover a Korean clinical skincare ritual designed for your skin stage and concern.": "Trả lời vài câu hỏi để khám phá nghi thức chăm sóc da lâm sàng Hàn Quốc được thiết kế cho tình trạng và vấn đề da của bạn.",
  "Clinical Korean cosmetic ritual": "Nghi thức mỹ phẩm lâm sàng Hàn Quốc",
  "Spa-use recovery guidance": "Hướng dẫn phục hồi chuẩn spa",
  "Clinical Formula Logic": "Logic công thức lâm sàng",
  "Cellular regeneration & recovery": "Phục hồi & hỗ trợ làm mới làn da",
  "A rich yet lightweight cream that deeply nourishes while encouraging cellular renewal for visibly rejuvenated skin.": "Chất kem đậm đặc nhưng mỏng nhẹ, hỗ trợ nuôi dưỡng chuyên sâu và cải thiện vẻ tươi mới cho làn da rạng rỡ hơn.",
  "A soothing gel formulated with a seven-extract Cica complex to calm reactive skin and restore the protective barrier.": "Gel làm dịu da với phức hợp Cica 7 chiết xuất, hỗ trợ làm dịu làn da nhạy cảm và củng cố hàng rào bảo vệ da.",
  "A next-generation ampoule harnessing Exosome technology and plant-derived Bakuchiol for visible skin renewal without irritation.": "Tinh chất thế hệ mới ứng dụng công nghệ Exosome và Bakuchiol nguồn gốc thực vật, hỗ trợ cải thiện vẻ tươi mới của làn da theo hướng êm dịu hơn.",
  "A high-performance moisturizer delivering an immediate and sustained surge of hydration for plumper, smoother skin.": "Kem dưỡng ẩm hiệu suất cao mang lại nguồn độ ẩm tức thì và duy trì dài lâu cho làn da căng mọng, mịn màng hơn.",
  "A lightweight preparatory toner that balances, hydrates, and primes the skin to maximize subsequent skincare absorption.": "Toner chuẩn bị với kết cấu mỏng nhẹ giúp cân bằng, cấp ẩm và tạo bước đệm hoàn hảo để tối đa hóa sự hấp thụ dưỡng chất sau đó.",
  "Clinical Formulas": "Công thức lâm sàng",
  "The Collection": "Bộ sưu tập",
  "Begin with a gentle clinical cleanser to remove impurities without disrupting the skin microbiome.": "Bắt đầu với bước làm sạch dịu nhẹ để loại bỏ tạp chất mà vẫn hỗ trợ duy trì cảm giác cân bằng tự nhiên của da.",
  "P30 Boost Facial Hydrating Toner — balance pH and prime for maximum absorption.": "P30 Boost Facial Hydrating Toner — cân bằng độ pH và tạo bước đệm tối đa hóa khả năng hấp thụ dưỡng chất.",
  "Gentle Activation Renew Ampoule — activate cellular renewal and luminosity.": "Gentle Activation Renew Ampoule — hỗ trợ quá trình làm mới làn da và cải thiện vẻ rạng rỡ.",
  "Sheer Gel / Recovery Care": "Sheer Gel / Chăm sóc phục hồi",
  "Calmiance Superior Sheer Gel — calm, protect, and fortify the skin barrier.": "Calmiance Superior Sheer Gel — làm dịu, bảo vệ và củng cố hàng rào bảo vệ da.",
  "Daily Clinical Ritual": "Nghi thức lâm sàng hàng ngày",
  "Barrier Recovery Ritual": "Nghi thức phục hồi hàng rào bảo vệ",
  "A calming recovery routine designed to restore skin comfort, hydration, and resilience.": "Quy trình phục hồi làm dịu, hỗ trợ khôi phục cảm giác dễ chịu, độ ẩm và khả năng tự bảo vệ của làn da.",
  "A lightweight clinical hydration routine to plump, smooth and refresh dehydrated skin.": "Quy trình cấp ẩm lâm sàng mỏng nhẹ giúp làm căng mọng, mịn màng và tươi mới làn da thiếu nước.",
  "An advanced regenerative skincare regimen to improve cell turnover, firmness, and reduce fine lines.": "Phác đồ chăm sóc chuyên sâu, hỗ trợ quá trình làm mới bề mặt da, cải thiện cảm giác săn chắc và làm mềm vẻ xuất hiện của nếp nhăn nhỏ.",
  "Radiance Recovery": "Phục hồi độ rạng rỡ",
  "Korean Recovery Ritual": "Nghi thức phục hồi Hàn Quốc",
  "PRODUCT INFORMATION": "THÔNG TIN SẢN PHẨM",
  "Focused recovery care for barrier, hydration and radiance.": "Chăm sóc phục hồi chuyên sâu cho hàng rào bảo vệ, độ ẩm và sự rạng rỡ.",
  "Supports healthy skin hydration and balances pH levels after cleansing.": "Hỗ trợ độ ẩm khỏe mạnh và cân bằng độ pH sau khi rửa mặt.",
  "Helps improve appearance of skin tone and texture with active technology.": "Hỗ trợ cải thiện vẻ ngoài của tông da và kết cấu da nhờ công nghệ hoạt chất.",
  "Supports skin barrier recovery and helps maintain natural resilience.": "Hỗ trợ phục hồi hàng rào bảo vệ da và duy trì sức đề kháng tự nhiên.",
  "Helps skin feel smoother and retains moisture for long-lasting hydration.": "Giúp làn da có cảm giác mịn màng hơn và hỗ trợ duy trì độ ẩm dài lâu.",
  "ACTIVE INGREDIENTS": "THÀNH PHẦN HOẠT CHẤT",
  "Aqua, Glycerin, Collagen Water, Peptide Complex, Hyaluronic Acid, Berry Complex Extracts and other cosmetic ingredients. Please refer to the product packaging for the complete ingredient list.": "Aqua, Glycerin, Collagen Water, Peptide Complex, Hyaluronic Acid, Berry Complex Extracts và các thành phần mỹ phẩm khác. Vui lòng tham khảo bao bì sản phẩm để xem danh sách thành phần đầy đủ.",
  "Collagen Water, Exosome, Peptide Complex, Hyaluronic Acid, Glycerin and other cosmetic ingredients. Please refer to the product packaging for the complete ingredient list.": "Collagen Water, Exosome, Peptide Complex, Hyaluronic Acid, Glycerin và các thành phần mỹ phẩm khác. Vui lòng tham khảo bao bì sản phẩm để xem danh sách thành phần đầy đủ.",
  "Focused delivery support for recovery-oriented skincare.": "Hỗ trợ dẫn truyền chuyên sâu cho quy trình chăm sóc da định hướng phục hồi.",
  "Skin recovery ritual tailored to individual skin concerns": "Nghi thức phục hồi da được thiết kế riêng cho từng vấn đề da",
  "Professional treatment compatibility for spa and clinic use": "Phù hợp với quy trình chăm sóc chuyên nghiệp tại spa và clinic",
  "Personalized care guidance from certified skincare specialists": "Hướng dẫn chăm sóc cá nhân hóa từ các chuyên gia chăm sóc da",
  "A personalized skincare experience designed for spa, clinic, and professional treatment environments — where expertise meets Korean clinical precision.": "Trải nghiệm chăm sóc da cá nhân hóa dành cho spa, clinic và môi trường chăm sóc chuyên nghiệp — nơi chuyên môn kết hợp cùng sự chính xác theo định hướng Hàn Quốc.",
  "Explore the Ritual": "Khám phá nghi thức",
  "A complete recovery set designed to support the skin barrier and restore a luminous, balanced appearance.": "Bộ sản phẩm phục hồi toàn diện được thiết kế để hỗ trợ hàng rào bảo vệ da và khôi phục vẻ ngoài cân bằng, rạng rỡ."
} as const;

export const COSMETIC_COPY_PROTECTED_PHRASES = [
  "VAVAW",
  "VAVAW Cosmetic",
  "VAVAW Beauty & Co",
  "VAVAW Franchise",
  "Luminous Revitalization Sheer Set",
  "CELLUREVIVE Ampoule",
  "REGENAGLOW NOURISH SHEER CREAM",
  "Calmiance Superior Sheer Gel",
  "P30 Boost Facial Hydrating Toner",
  "Gentle Activation Renew Ampoule",
  "P30 Boost Facial Moisturizer",
  "LUMIGLOW ROSY SHEER SUNSCREEN",
  "EXOSOME",
  "COLLAGEN",
  "RAW"
];

export const COSMETIC_COPY_PROTECTED_KEYS = [
  "href",
  "url",
  "src",
  "image",
  "imageUrl",
  "mediaSlot",
  "videoSlot",
  "slug",
  "path",
  "page_path",
  "block_type",
  "canonical",
  "canonicalUrl",
  "productSlug",
  "route",
  "id",
  "key",
  "icon"
];
