export const COSMETIC_VI_COPY_MAP = {
  "The Premium RAW Skincare System": "Hệ thống chăm sóc da RAW cao cấp",
  "Scientific beauty, refined into a pure Korean skincare ritual.": "Vẻ đẹp khoa học, được tinh chỉnh thành nghi thức chăm sóc da Hàn Quốc thuần khiết.",
  "Scientific Beauty": "Vẻ đẹp khoa học",
  "Premium Program": "Chương trình chăm sóc cao cấp",
  "Functional Cosmetics": "Mỹ phẩm chức năng",
  "SIGNATURE RECOVERY COLLECTION": "BỘ SẢN PHẨM PHỤC HỒI ĐẶC TRƯNG",
  "Signature Recovery Collection": "Bộ sản phẩm phục hồi đặc trưng",
  "A complete Korean clinical skincare ritual for recovery, hydration, radiance, and skin barrier support.": "Nghi thức chăm sóc da Hàn Quốc định hướng lâm sàng, hỗ trợ phục hồi, cấp ẩm, cải thiện vẻ rạng rỡ và củng cố hàng rào bảo vệ da.",
  "EXPLORE THE RITUAL": "KHÁM PHÁ NGHI THỨC",
  "CLINICAL INSIGHT": "GÓC NHÌN LÂM SÀNG",
  "FEATURED SET": "BỘ SẢN PHẨM NỔI BẬT",
  "RECOVERY RITUAL · 6 STEPS": "NGHI THỨC PHỤC HỒI · 6 BƯỚC",
  "PEPTIDE COMPLEX": "PHỨC HỢP PEPTIDE",
  "VAVAW is a clinical Korean cosmetic system designed to restore the skin from its origin — pure, balanced, and resilient.": "VAVAW là hệ mỹ phẩm Hàn Quốc định hướng lâm sàng, được phát triển để hỗ trợ làn da phục hồi từ nền tảng — tinh khiết, cân bằng và bền vững.",
  "Clinical skincare system shaped by professional care standards — developed for visible, lasting results.": "Hệ chăm sóc da định hướng lâm sàng, được phát triển theo tiêu chuẩn chăm sóc chuyên nghiệp để mang lại hiệu quả rõ ràng và bền vững.",
  "Personalized skincare experience for modern skin concerns — designed for spa, clinic, and home ritual.": "Trải nghiệm chăm sóc da cá nhân hóa cho các vấn đề da hiện đại — phù hợp cho spa, clinic và routine tại nhà.",
  "Korean-developed formulas designed for visible skin recovery, balancing efficacy with elegance.": "Công thức phát triển theo định hướng Hàn Quốc, hỗ trợ phục hồi làn da rõ rệt và cân bằng giữa hiệu quả với sự tinh tế.",
  "The complete skin\nrecovery ritual.": "Nghi thức phục hồi da\ntoàn diện.",
  "A complete Korean clinical skincare ritual designed to cleanse, prepare, treat, seal, and protect the skin.": "Nghi thức chăm sóc da lâm sàng Hàn Quốc toàn diện được thiết kế để làm sạch, chuẩn bị, đặc trị, khóa ẩm và bảo vệ da.",
  "SIGNATURE RECOVERY SYSTEM": "HỆ THỐNG PHỤC HỒI ĐẶC TRƯNG",
  "Daily Clinical Skincare Routine": "Nghi thức chăm sóc da lâm sàng hàng ngày",
  "Answer a few quick questions to discover a Korean clinical skincare ritual designed for your skin stage and concern.": "Trả lời vài câu hỏi để khám phá nghi thức chăm sóc da lâm sàng Hàn Quốc được thiết kế cho tình trạng và vấn đề da của bạn."
} as const;

export const COSMETIC_COPY_PROTECTED_PHRASES = [
  "VAVAW",
  "VAVAW Cosmetic",
  "VAVAW Beauty & Co",
  "VAVAW Franchise",
  "Luminous Revitalization Sheer Set",
  "CELLUREVIVE Ampoule",
  "REGENAGLOW NOURISH SHEER CREAM",
  "Calmiance Superior Sheer Gel",
  "P30 Boost Facial Hydrating Toner",
  "Gentle Activation Renew Ampoule",
  "P30 Boost Facial Moisturizer",
  "LUMIGLOW ROSY SHEER SUNSCREEN",
  "EXOSOME",
  "COLLAGEN",
  "RAW"
];

export const COSMETIC_COPY_PROTECTED_KEYS = [
  "href",
  "url",
  "src",
  "image",
  "imageUrl",
  "mediaSlot",
  "videoSlot",
  "slug",
  "path",
  "page_path",
  "block_type",
  "canonical",
  "canonicalUrl",
  "productSlug",
  "route",
  "id",
  "key",
  "icon"
];
